### ISSUE TITLE
geo loader opens two metadata form editors

### ISSUE THREAD

**Issue by erikradio** [culibraries/geoDataLoader#12] opened 2019-02-25 22:03 UTC
When I imported this dataset, the loader opened two metadata forms:

https://drive.google.com/open?id=1BI1FMW41iHpUc9iBEdWhbH1d6wIUuYN3

**Comment by mbstacy** [comment] 2019-03-01 16:39
@erikradio I'm not able to reproduce two metadata forms. Can you try again and see if it happens again? Thanks, Mark

**Comment by erikradio** [comment] 2019-03-04 15:44
couldn't recreate it. prob ok to close this and will let you know if i see it again

**Comment by mbstacy** [comment] 2019-03-04 21:07
Closing issue.

**Closed as completed by mbstacy** 2019-03-04 21:07 UTC
Labels: bug
